export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_PAYMENT_VNPAY_REQUEST = 'ORDER_PAYMENT_VNPAY_REQUEST'
export const ORDER_PAYMENT_VNPAY_SUCCESS = 'ORDER_PAYMENT_VNPAY_SUCCESS'
export const ORDER_PAYMENT_VNPAY_FAIL = 'ORDER_PAYMENT_VNPAY_FAIL'
export const ORDER_PAYMENT_VNPAY_RESET = 'ORDER_PAYMENT_VNPAY_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';



