/** @format */

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const OPEN_MODAL_SEARCH = "OPEN_MODAL_SEARCH";
export const CLOSE_MODAL_SEARCH = "CLOSE_MODAL_SEARCH";

export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";

export const PRODUCT_FILTERS_CATEGORY_REQUEST =
  "PRODUCT_FILTERS_CATEGORY_REQUEST";
export const PRODUCT_FILTERS_CATEGORY_SUCCESS =
  "PRODUCT_FILTERS_CATEGORY_SUCCESS";
export const PRODUCT_FILTERS_CATEGORY_FAIL = "PRODUCT_FILTERS_CATEGORY_FAIL";

export const PRODUCT_FILTERS_PRICE_REQUEST = "PRODUCT_FILTERS_PRICE_REQUEST";
export const PRODUCT_FILTERS_PRICE_SUCCESS = "PRODUCT_FILTERS_PRICE_SUCCESS";
export const PRODUCT_FILTERS_PRICE_FAIL = "PRODUCT_FILTERS_PRICE_FAIL";

export const PRODUCT_FILTERS_RATING_REQUEST = "PRODUCT_FILTERS_RATING_REQUEST";
export const PRODUCT_FILTERS_RATING_SUCCESS = "PRODUCT_FILTERS_RATING_SUCCESS";
export const PRODUCT_FILTERS_RATING_FAIL = "PRODUCT_FILTERS_RATING_FAIL";

export const PRODUCT_FILTERS_COLOR_REQUEST = "PRODUCT_FILTERS_COLOR_REQUEST";
export const PRODUCT_FILTERS_COLOR_SUCCESS = "PRODUCT_FILTERS_COLOR_SUCCESS";
export const PRODUCT_FILTERS_COLOR_FAIL = "PRODUCT_FILTERS_COLOR_FAIL";

export const PRODUCT_PRICE_LOWEST_REQUEST = "PRODUCT_PRICE_LOWEST_REQUEST";
export const PRODUCT_PRICE_LOWEST_SUCCESS = "PRODUCT_PRICE_LOWEST_SUCCESS";
export const PRODUCT_PRICE_LOWEST_FAIL = "PRODUCT_PRICE_LOWEST_FAIL";

export const PRODUCT_PRICE_HIGHEST_REQUEST = "PRODUCT_PRICE_HIGHEST_REQUEST";
export const PRODUCT_PRICE_HIGHEST_SUCCESS = "PRODUCT_PRICE_HIGHEST_SUCCESS";
export const PRODUCT_PRICE_HIGHEST_FAIL = "PRODUCT_PRICE_HIGHEST_FAIL";

export const PRODUCT_SORT_BEST_RATING_REQUEST =
  "PRODUCT_SORT_BEST_RATING_REQUEST";
export const PRODUCT_SORT_BEST_RATING_SUCCESS =
  "PRODUCT_SORT_BEST_RATING_SUCCESS";
export const PRODUCT_SORT_BEST_RATING_FAIL = "PRODUCT_SORT_BEST_RATING_FAIL";

export const PRODUCT_SORT_NEWEST_REQUEST = "PRODUCT_SORT_NEWEST_REQUEST";
export const PRODUCT_SORT_NEWEST_SUCCESS = "PRODUCT_SORT_NEWEST_SUCCESS";
export const PRODUCT_SORT_NEWEST_FAIL = "PRODUCT_SORT_NEWEST_FAIL";
